# HTTP only — run certbot after nginx reload:
# sudo certbot --nginx -d hr-event-tracker.schoepels.com

server {
    listen 80;
    listen [::]:80;

    server_name hr-event-tracker.schoepels.com;

    client_max_body_size 20M;

    # logging
    access_log /var/log/nginx/hr-event-tracker.schoepels.com.access.log;
    error_log /var/log/nginx/hr-event-tracker.schoepels.com.error.log warn;

    # reverse proxy
    location / {
        include nginxconfig.io/restrict.conf;
        proxy_pass http://10.0.10.60:3000;
        include nginxconfig.io/proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}
